### ISSUE TITLE
Sort decompositions according to length

### ISSUE THREAD

**Issue by abunickabhi** [nbwzx/commutator#3]
The various decompositions that are generated for the algorithm are of varying lengths.

Most of the time, the shortest decomposition is at the top, but that is usually not the case.

It would be preferable if the decompositions are sorted according to their string length (including brackets).

**Comment by nbwzx** [comment]
The sorting rules are here (https://github.com/nbwzx/commutator/blob/7ce8c22d5c5706049cd3fc506b54dc9420b562eb/assets/dist/js/cube.js#L214-L228). What you mean is that abMaxScore = abMinScore = 1.  

However, what I use is abMaxScore = 2.5 and abMinScore = 5. Take R2 D' R2 U' R U R2 D R2 U' R' U for example. Usually we prefer R2:[D',R2 U' R U R2] (length 7) instead of [R2 D' R2,U' R U] (length 6) since shorter min(A,B) in [A,B] can show the alg structure better. And with my parameters, the score of the first one is 18.5 and the score of the second one is 22.5 so we choose the first one.

Admittedly, different people have different preferences regarding these parameters. I'll add them to the settings to customize these parameters later.

**Comment by nbwzx** [comment]
Well, now you can customize these parameters. I think set both parameters to 1 is what you wanted. ([relevant commit](https://github.com/nbwzx/commutator/commit/7ed98c4d6564b5bc1bbc7db414e9f73dee2f121f))

**Comment by nbwzx** [comment]
Has the problem been resolved? If so, I may close this issue. @abunickabhi

**Comment by abunickabhi** [comment]
Yes problem has been resolved, sorting rules is different by the way you count. I get it.
